version: 2.1

executors:
  android-executor:
    docker:
      - image: circleci/android:api-29

jobs:
  build:
    executor: android-executor
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-

      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies

      - save_cache:
          paths:
            - ~/.gradle/caches/
            - ~/.gradle/wrapper/
          key: v1-dependencies-{{ checksum "build.gradle" }}

      # Build the project
      - run:
          name: Assemble Debug
          command: ./gradlew assembleDebug

      # Store build outputs
      - store_artifacts:
          path: app/build/outputs/apk/debug/
          destination: apks

      #Run unit tests
      - run:
          name: Run Unit Tests
          command: ./gradlew test

      # Store test results
      - store_test_results:
          path: app/build/test-results/testDebugUnitTest

      - store_artifacts:
          path: app/build/reports/tests/testDebugUnitTest

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
