version: 2.1

executors:
  android-executor:
    docker:
      - image: circleci/android:api-29
    environment:
      JAVA_HOME: /usr/lib/jvm/java-17-openjdk
      PATH: /usr/lib/jvm/java-17-openjdk/bin/:$PATH
    working_directory: ~/project

jobs:
  build:
    executor: android-executor
    steps:
      - checkout

      # Ensure gradlew has execute permissions
      - run:
          name: Grant execute permission for gradlew
          command: chmod +x ./gradlew

      #Set up JDK 17
      - run:
          name: Install JDK 17
          command: |
            sudo apt-get update
            sudo apt-get install -y openjdk-17-jdk
            sudo update-alternatives --set java /usr/lib/jvm/java-17-openjdk-amd64/bin/java
            sudo update-alternatives --set javac /usr/lib/jvm/java-17-openjdk-amd64/bin/javac

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "app/build.gradle" }}
            - v1-dependencies-

      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies

      - save_cache:
          paths:
            - ~/.gradle/caches/
            - ~/.gradle/wrapper/
          key: v1-dependencies-{{ checksum "app/build.gradle" }}

      # Build the project
      - run:
          name: Assemble Debug
          command: ./gradlew assembleDebug

      # Store build outputs
      - store_artifacts:
          path: app/build/outputs/apk/debug/
          destination: apks

      # Run unit tests
      - run:
          name: Run Unit Tests
          command: ./gradlew test

      # Store test results
      - store_test_results:
          path: app/build/test-results/testDebugUnitTest

      - store_artifacts:
          path: app/build/reports/tests/testDebugUnitTest

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
