name: Android CD

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Grant execute permission for Gradle wrapper
        run: chmod +x gradlew
      - name: Build with Gradle and Sign APK
        run: ./gradlew assembleRelease
      - name: Verify APK Path
        run: ls -R app/build/outputs/apk/release
      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: app-release.apk
          path: app/build/outputs/apk/release/app-release.apk

  distribute:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: app-release.apk
      - name: Install Firebase CLI
        run: npm install -g firebase-tools
      - name: Distribute via Firebase App Distribution
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: firebase appdistribution:distribute app-release.apk --app schedule-app-b767c --groups hlev2454@gmail.com
