name: Android CD

on:
  push:
    branches:
      - main  # Adjust the branch to your main branch

permissions:
  contents: write  # Adjusting permissions for GITHUB_TOKEN

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Grant execute permission for Gradle wrapper
        run: chmod +x gradlew
      - name: Build with Gradle and Sign APK
        run: ./gradlew assembleRelease
      - name: Verify APK Path
        run: ls -R app/build/outputs/apk/release
      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: app-release.apk
          path: app/build/outputs/apk/release/app-release.apk

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: app-release.apk
      - name: Install Firebase CLI
        run: npm install -g firebase-tools
      - name: Copy firebase.json to root
        run: cp .github/firebase.json .
      - name: Print current directory
        run: pwd
      - name: List all files in current directory
        run: ls -al
      - name: List all files in the .github directory
        run: ls -al .github
      - name: Deploy to Firebase
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: firebase deploy --only hosting --token "${{ secrets.FIREBASE_TOKEN }}"
