name: Android CD

on:
  push:
    branches:
      - main  # Adjust the branch to your main branch
permissions:
  contents: write  # Adjusting permissions for GITHUB_TOKEN
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Grant execute permission for Gradle wrapper
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew assembleRelease

      - name: Verify APK Path
        run: ls -R app/build/outputs/apk/release

      - name: Decode Keystore
        run: echo "${{ secrets.KEYSTORE }}" | base64 -d > release-key.jks

      - name: Sign APK
        run: |
          jarsigner -verbose -sigalg SHA256withRSA -digestalg SHA-256 \
          -keystore release-key.jks \
          -storepass ${{ secrets.KEYSTORE_PASSWORD }} \
          -keypass ${{ secrets.KEY_PASSWORD }} \
          app/build/outputs/apk/release/app-release-unsigned.apk \
          ${{ secrets.KEY_ALIAS }}
      - name: Verify Signed APK
        run: jarsigner -verify app/build/outputs/apk/release/app-release-unsigned.apk

      - name: Set up Android SDK
        uses: reactivecircus/setup-android@v2
        with:
            sdk-platform: 'platforms;android-30'  # Adjust the SDK platform version as needed
            build-tools: '30.0.3'  # Adjust the build tools version as needed

      - name: Zipalign APK
        run: |
          $ANDROID_SDK_ROOT/build-tools/30.0.3/zipalign -v 4 \
          app/build/outputs/apk/release/app-release-unsigned.apk \
          app/build/outputs/apk/release/app-release.apk

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: app-release.apk
          path: app/build/outputs/apk/release/app-release.apk
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: app-release.apk
      - name: Install Firebase CLI
        run: npm install -g firebase-tools
      - name: Authenticate to Firebase
        run: firebase auth:login:ci --token ${{ secrets.FIREBASE_TOKEN }}
      - name: Deploy to Firebase
        run: firebase deploy --only hosting
